// Copyright 2009, 2015 by Peter Ohler, All Rights Reserved

#ifndef __OFIX_TAG_H__
#define __OFIX_TAG_H__

#define OFIX_AccountTAG					1
#define OFIX_AdvIdTAG					2
#define OFIX_AdvRefIDTAG				3
#define OFIX_AdvSideTAG					4
#define OFIX_AdvTransTypeTAG				5
#define OFIX_AvgPxTAG					6
#define OFIX_BeginSeqNoTAG				7
#define OFIX_BeginStringTAG				8
#define OFIX_BodyLengthTAG				9
#define OFIX_CheckSumTAG				10
#define OFIX_ClOrdIDTAG					11
#define OFIX_CommissionTAG				12
#define OFIX_CommTypeTAG				13
#define OFIX_CumQtyTAG					14
#define OFIX_CurrencyTAG				15
#define OFIX_EndSeqNoTAG				16
#define OFIX_ExecIDTAG					17
#define OFIX_ExecInstTAG				18
#define OFIX_ExecRefIDTAG				19
#define OFIX_ExecTransTypeTAG				20
#define OFIX_HandlInstTAG				21
#define OFIX_IDSourceTAG				22
#define OFIX_SecurityIDSourceTAG			22
#define OFIX_IOIidTAG					23
#define OFIX_IOIOthSvcTAG				24
#define OFIX_IOIQltyIndTAG				25
#define OFIX_IOIRefIDTAG				26
#define OFIX_IOIQtyTAG					27
#define OFIX_IOISharesTAG				27
#define OFIX_IOITransTypeTAG				28
#define OFIX_LastCapacityTAG				29
#define OFIX_LastMktTAG					30
#define OFIX_LastPxTAG					31
#define OFIX_LastQtyTAG					32
#define OFIX_LastSharesTAG				32
#define OFIX_LinesOfTextTAG				33
#define OFIX_MsgSeqNumTAG				34
#define OFIX_MsgTypeTAG					35
#define OFIX_NewSeqNoTAG				36
#define OFIX_OrderIDTAG					37
#define OFIX_OrderQtyTAG				38
#define OFIX_OrdStatusTAG				39
#define OFIX_OrdTypeTAG					40
#define OFIX_OrigClOrdIDTAG				41
#define OFIX_OrigTimeTAG				42
#define OFIX_PossDupFlagTAG				43
#define OFIX_PriceTAG					44
#define OFIX_RefSeqNumTAG				45
#define OFIX_RelatdSymTAG				46
#define OFIX_Rule80ATAG					47
#define OFIX_SecurityIDTAG				48
#define OFIX_SenderCompIDTAG				49
#define OFIX_SenderSubIDTAG				50
#define OFIX_SendingDateTAG				51
#define OFIX_SendingTimeTAG				52
#define OFIX_QuantityTAG				53
#define OFIX_SharesTAG					53
#define OFIX_SideTAG					54
#define OFIX_SymbolTAG					55
#define OFIX_TargetCompIDTAG				56
#define OFIX_TargetSubIDTAG				57
#define OFIX_TextTAG					58
#define OFIX_TimeInForceTAG				59
#define OFIX_TransactTimeTAG				60
#define OFIX_UrgencyTAG					61
#define OFIX_ValidUntilTimeTAG				62
#define OFIX_SettlTypeTAG				63
#define OFIX_SettlmntTypTAG				63
#define OFIX_FutSettDateTAG				64
#define OFIX_SettlDateTAG				64
#define OFIX_SymbolSfxTAG				65
#define OFIX_ListIDTAG					66
#define OFIX_ListSeqNoTAG				67
#define OFIX_ListNoOrdsTAG				68
#define OFIX_TotNoOrdersTAG				68
#define OFIX_ListExecInstTAG				69
#define OFIX_AllocIDTAG					70
#define OFIX_AllocTransTypeTAG				71
#define OFIX_RefAllocIDTAG				72
#define OFIX_NoOrdersTAG				73
#define OFIX_AvgPrxPrecisionTAG				74
#define OFIX_AvgPxPrecisionTAG				74
#define OFIX_TradeDateTAG				75
#define OFIX_ExecBrokerTAG				76
#define OFIX_OpenCloseTAG				77
#define OFIX_PositionEffectTAG				77
#define OFIX_NoAllocsTAG				78
#define OFIX_AllocAccountTAG				79
#define OFIX_AllocQtyTAG				80
#define OFIX_AllocSharesTAG				80
#define OFIX_ProcessCodeTAG				81
#define OFIX_NoRptsTAG					82
#define OFIX_RptSeqTAG					83
#define OFIX_CxlQtyTAG					84
#define OFIX_NoDlvyInstTAG				85
#define OFIX_DlvyInstTAG				86
#define OFIX_AllocStatusTAG				87
#define OFIX_AllocRejCodeTAG				88
#define OFIX_SignatureTAG				89
#define OFIX_SecureDataLenTAG				90
#define OFIX_SecureDataTAG				91
#define OFIX_BrokerOfCreditTAG				92
#define OFIX_SignatureLengthTAG				93
#define OFIX_EmailTypeTAG				94
#define OFIX_RawDataLengthTAG				95
#define OFIX_RawDataTAG					96
#define OFIX_PossResendTAG				97
#define OFIX_EncryptMethodTAG				98
#define OFIX_StopPxTAG					99
#define OFIX_ExDestinationTAG				100
#define OFIX_CxlRejReasonTAG				102
#define OFIX_OrdRejReasonTAG				103
#define OFIX_IOIQualifierTAG				104
#define OFIX_WaveNoTAG					105
#define OFIX_IssuerTAG					106
#define OFIX_SecurityDescTAG				107
#define OFIX_HeartBtIntTAG				108
#define OFIX_ClientIDTAG				109
#define OFIX_MinQtyTAG					110
#define OFIX_MaxFloorTAG				111
#define OFIX_TestReqIDTAG				112
#define OFIX_ReportToExchTAG				113
#define OFIX_LocateReqdTAG				114
#define OFIX_OnBehalfOfCompIDTAG			115
#define OFIX_OnBehalfOfSubIDTAG				116
#define OFIX_QuoteIDTAG					117
#define OFIX_NetMoneyTAG				118
#define OFIX_SettlCurrAmtTAG				119
#define OFIX_SettlCurrencyTAG				120
#define OFIX_ForexReqTAG				121
#define OFIX_OrigSendingTimeTAG				122
#define OFIX_GapFillFlagTAG				123
#define OFIX_NoExecsTAG					124
#define OFIX_CxlTypeTAG					125
#define OFIX_ExpireTimeTAG				126
#define OFIX_DKReasonTAG				127
#define OFIX_DeliverToCompIDTAG				128
#define OFIX_DeliverToSubIDTAG				129
#define OFIX_IOINaturalFlagTAG				130
#define OFIX_QuoteReqIDTAG				131
#define OFIX_BidPxTAG					132
#define OFIX_OfferPxTAG					133
#define OFIX_BidSizeTAG					134
#define OFIX_OfferSizeTAG				135
#define OFIX_NoMiscFeesTAG				136
#define OFIX_MiscFeeAmtTAG				137
#define OFIX_MiscFeeCurrTAG				138
#define OFIX_MiscFeeTypeTAG				139
#define OFIX_PrevClosePxTAG				140
#define OFIX_ResetSeqNumFlagTAG				141
#define OFIX_SenderLocationIDTAG			142
#define OFIX_TargetLocationIDTAG			143
#define OFIX_OnBehalfOfLocationIDTAG			144
#define OFIX_DeliverToLocationIDTAG			145
#define OFIX_NoRelatedSymTAG				146
#define OFIX_SubjectTAG					147
#define OFIX_HeadlineTAG				148
#define OFIX_URLLinkTAG					149
#define OFIX_ExecTypeTAG				150
#define OFIX_LeavesQtyTAG				151
#define OFIX_CashOrderQtyTAG				152
#define OFIX_AllocAvgPxTAG				153
#define OFIX_AllocNetMoneyTAG				154
#define OFIX_SettlCurrFxRateTAG				155
#define OFIX_SettlCurrFxRateCalcTAG			156
#define OFIX_NumDaysInterestTAG				157
#define OFIX_AccruedInterestRateTAG			158
#define OFIX_AccruedInterestAmtTAG			159
#define OFIX_SettlInstModeTAG				160
#define OFIX_AllocTextTAG				161
#define OFIX_SettlInstIDTAG				162
#define OFIX_SettlInstTransTypeTAG			163
#define OFIX_EmailThreadIDTAG				164
#define OFIX_SettlInstSourceTAG				165
#define OFIX_SettlLocationTAG				166
#define OFIX_SecurityTypeTAG				167
#define OFIX_EffectiveTimeTAG				168
#define OFIX_StandInstDbTypeTAG				169
#define OFIX_StandInstDbNameTAG				170
#define OFIX_StandInstDbIDTAG				171
#define OFIX_SettlDeliveryTypeTAG			172
#define OFIX_SettlDepositoryCodeTAG			173
#define OFIX_SettlBrkrCodeTAG				174
#define OFIX_SettlInstCodeTAG				175
#define OFIX_SecuritySettlAgentNameTAG			176
#define OFIX_SecuritySettlAgentCodeTAG			177
#define OFIX_SecuritySettlAgentAcctNumTAG		178
#define OFIX_SecuritySettlAgentAcctNameTAG		179
#define OFIX_SecuritySettlAgentContactNameTAG		180
#define OFIX_SecuritySettlAgentContactPhoneTAG		181
#define OFIX_CashSettlAgentNameTAG			182
#define OFIX_CashSettlAgentCodeTAG			183
#define OFIX_CashSettlAgentAcctNumTAG			184
#define OFIX_CashSettlA