// Copyright 2009, 2015 by Peter Ohler, All Rights Reserved

#ifndef __OFIX_TAG_H__
#define __OFIX_TAG_H__

#define OFIX_AccountTAG					1
#define OFIX_AdvIdTAG					2
#define OFIX_AdvRefIDTAG				3
#define OFIX_AdvSideTAG					4
#define OFIX_AdvTransTypeTAG				5
#define OFIX_AvgPxTAG					6
#define OFIX_BeginSeqNoTAG				7
#define OFIX_BeginStringTAG				8
#define OFIX_BodyLengthTAG				9
#define OFIX_CheckSumTAG				10
#define OFIX_ClOrdIDTAG					11
#define OFIX_CommissionTAG				12
#define OFIX_CommTypeTAG				13
#define OFIX_CumQtyTAG					14
#define OFIX_CurrencyTAG				15
#define OFIX_EndSeqNoTAG				16
#define OFIX_ExecIDTAG					17
#define OFIX_ExecInstTAG				18
#define OFIX_ExecRefIDTAG				19
#define OFIX_ExecTransTypeTAG				20
#define OFIX_HandlInstTAG				21
#define OFIX_IDSourceTAG				22
#define OFIX_SecurityIDSourceTAG			22
#define OFIX_IOIidTAG					23
#define OFIX_IOIOthSvcTAG				24
#define OFIX_IOIQltyIndTAG				25
#define OFIX_IOIRefIDTAG				26
#define OFIX_IOIQtyTAG					27
#define OFIX_IOISharesTAG				27
#define OFIX_IOITransTypeTAG				28
#define OFIX_LastCapacityTAG				29
#define OFIX_LastMktTAG					30
#define OFIX_LastPxTAG					31
#define OFIX_LastQtyTAG					32
#define OFIX_LastSharesTAG				32
#define OFIX_LinesOfTextTAG				33
#define OFIX_MsgSeqNumTAG				34
#define OFIX_MsgTypeTAG					35
#define OFIX_NewSeqNoTAG				36
#define OFIX_OrderIDTAG					37
#define OFIX_OrderQtyTAG				38
#define OFIX_OrdStatusTAG				39
#define OFIX_OrdTypeTAG					40
#define OFIX_OrigClOrdIDTAG				41
#define OFIX_OrigTimeTAG				42
#define OFIX_PossDupFlagTAG				43
#define OFIX_PriceTAG					44
#define OFIX_RefSeqNumTAG				45
#define OFIX_RelatdSymTAG				46
#define OFIX_Rule80ATAG					47
#define OFIX_SecurityIDTAG				48
#define OFIX_SenderCompIDTAG				49
#define OFIX_SenderSubIDTAG				50
#define OFIX_SendingDateTAG				51
#define OFIX_SendingTimeTAG				52
#define OFIX_QuantityTAG				53
#define OFIX_SharesTAG					53
#define OFIX_SideTAG					54
#define OFIX_SymbolTAG					55
#define OFIX_TargetCompIDTAG				56
#define OFIX_TargetSubIDTAG				57
#define OFIX_TextTAG					58
#define OFIX_TimeInForceTAG				59
#define OFIX_TransactTimeTAG				60
#define OFIX_UrgencyTAG					61
#define OFIX_ValidUntilTimeTAG				62
#define OFIX_SettlTypeTAG				63
#define OFIX_SettlmntTypTAG				63
#define OFIX_FutSettDateTAG				64
#define OFIX_SettlDateTAG				64
#define OFIX_SymbolSfxTAG				65
#define OFIX_ListIDTAG					66
#define OFIX_ListSeqNoTAG				67
#define OFIX_ListNoOrdsTAG				68
#define OFIX_TotNoOrdersTAG				68
#define OFIX_ListExecInstTAG				69
#define OFIX_AllocIDTAG					70
#define OFIX_AllocTransTypeTAG				71
#define OFIX_RefAllocIDTAG				72
#define OFIX_NoOrdersTAG				73
#define OFIX_AvgPrxPrecisi